### ISSUE TITLE
GetVersionWithoutRevision throws an ArgumentNullException  if Chrome is not installed.

### ISSUE THREAD

**Issue by MichielDean** [rosolko/WebDriverManager.Net#102]
I think this would be a much better user experience if a custom exception, or at least an exception with a custom message were thrown. It could explicitly state that the Chrome installed version could not be found.

Here is the relevant portion of the stack trace. I ran this on a machine that did not have chome installed and this was the result:
```
System.ArgumentNullException : Value cannot be null.
Parameter name: input
   at System.Version.Parse(String input)
   at WebDriverManager.Helpers.VersionHelper.GetVersionWithoutRevision(String version)
   at WebDriverManager.DriverConfigs.Impl.ChromeConfig.GetMatchingBrowserVersion()
   at WebDriverManager.DriverManager.GetVersionToDownload(IDriverConfig config, String version)
   at WebDriverManager.DriverManager.SetUpDriver(IDriverConfig config, String version, Architecture architecture)
```

**Comment by MichielDean** [comment]
This is related to: https://github.com/rosolko/WebDriverManager.Net/pull/91
