### ISSUE TITLE
Directory.Move doesn't work on different volumes

### ISSUE THREAD

**Issue by BlinD-HuNTeR** [rosolko/WebDriverManager.Net#145]
Sorry for the brief description, but this is easy to understand:

After the commit from pull request #135, a mechanism was implemented to support concurrency, by atomically moving the temporary directory to the destination. Problem is, **Directory.Move()** doesn't work if the source and target directories are on different volumes.

As a workaround, I'm changing the TMP environment variable to a directory in the same volume, to avoid the problem.

To solve this bug without losing concurrency support, you can just put the staging directory on the same folder as the target, instead of using GetTempPath.

**Comment by aonorgate** [comment]
This is also affecting our setup when using an Azure pipeline where the package runs on a different volume to the browser.

**Comment by eatonjl** [comment]
> Directory.Move()

How do you change the TMP environment variable?

**Comment by BlinD-HuNTeR** [comment]
> How do you change the TMP environment variable?

Environment.SetEnvironmentVariable. I change it right before invoking SetupDriver, then restore the original value. Of course this is for Windows only.

**Comment by eatonjl** [comment]
Thank you!

**Comment by eatonjl** [comment]
> > How do you change the TMP environment variable?
> 
> Environment.SetEnvironmentVariable. I change it right before invoking SetupDriver, then restore the original value. Of course this is for Windows only.

I am trying to make this work, but I don't think I am understanding the concept. Could you show me how you implemented that? I am having no success on my code.

**Comment by FermJacob** [comment]
Issue is happening on GitHub agents as well

``` csharp
Your web driver may be out of date or unsupported.
    at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry) in D:\a\MAQS\MAQS\Framework\BaseSeleniumTest\WebDriverFactory.cs:line 514
    at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetHeadlessChromeDriver(TimeSpan commandTimeout, ChromeOptions headlessChromeOptions) in D:\a\MAQS\MAQS\Framework\BaseSeleniumTest\WebDriverFactory.cs:line 214
    at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.GetBrowserWithDefaultConfiguration(BrowserType browser) in D:\a\MAQS\MAQS\Framework\BaseSeleniumTest\WebDriverFactory.cs:line 66
   Error writing D:\a\MAQS\MAQS\artifactTests\Chrome\94.0.4606.61\X64
      at WebDriverManager.Services.Impl.BinaryService.SetupBinary(String url, String zipPath, String binaryPath)
    at WebDriverManager.DriverManager.SetUpDriverImpl(String url, String binaryPath)
    at WebDriverManager.DriverManager.SetUpDriver(IDriverConfig config, String version, Architecture architecture)
    at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.<>c__DisplayClass8_0.<GetHeadlessChromeDriver>b__0() in D:\a\MAQS\MAQS\Framework\BaseSeleniumTest\WebDriverFactory.cs:line 216
    at Magenic.Maqs.BaseSeleniumTest.WebDriverFactory.CreateDriver(Func`1 createFunction, Boolean retry) in D:\a\MAQS\MAQS\Framework\BaseSeleniumTest\WebDriverFactory.cs:line 486
     Source and destination path must have identical roots. Move will not work across volumes.
        at System.IO.Directory.Move(String sourceDirName, String destDirName)
    at WebDriverManager.Services.Impl.BinaryService.SetupBinary(String url, String zipPath, String binaryPath)
```

**Comment by FermJacob** [comment]
@BlinD-HuNTeR @aonorgate @rosolko 

Validated with the new NuGet package that my CI builds are passing
