### ISSUE TITLE
FileLoadException with `System.Text.Json` when upgrading to v2.17.0

### ISSUE THREAD

**Issue by imliuruiqi** [rosolko/WebDriverManager.Net#257]
When upgrading to v2.17.0, normally the `System.Text.Json` will be upgraded to `7.0.3`, however when trying to run it seem that WebDriverManager is trying to use System.Text.Json 7.0.0

```C#
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'WebDriverManager.Clients.ChromeForTestingClient' threw an exception.
  Source=WebDriverManager
  StackTrace:
   at WebDriverManager.Clients.ChromeForTestingClient.GetKnownGoodVersionsWithDownloads()
   at WebDriverManager.DriverConfigs.Impl.ChromeConfig.GetVersionFromChromeForTestingApi(String noRevisionVersion)
   at WebDriverManager.DriverConfigs.Impl.ChromeConfig.GetMatchingBrowserVersion()
   at ** in **.cs:line 129

  This exception was originally thrown at this call stack:

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
PS: please ignore the `**` symbol in the exeception above.

**Comment by imliuruiqi** [comment]
seems to be a problem of Visual Studio. Closed.

**Comment by jduust** [comment]
I have the same issue with UiPath, how was it resolved? 
@imliuruiqi

**Comment by imliuruiqi** [comment]
> I have the same issue with UiPath, how was it resolved? @imliuruiqi

clean up the project, remove this package from project, then clean up downloaded package, do dotnet restore, then add this package back.
