### ISSUE TITLE
SetUpDriver attempting to write to Group Policy Directory

### ISSUE THREAD

**Issue by rneal4** [rosolko/WebDriverManager.Net#265]
I'm getting the following error on small number of my test machines because it's attempting to write to the Group Policy Directory. The rest of the test machines on the same group policy are running fine with no issues. Is there any information on what WebDriverManager is attempting to do here, why, and if needed how to prevent it?

Access to the path '\\MyDomain\SysVol\MyDomain\Policies\{7C08FC26-04F8-45E3-8FA5-4F17014B4DE2}\User\Scripts\Logon\Chrome\116.0.5845.96\X64' is denied.

at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)

at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)

at System.IO.Directory.CreateDirectory(String path)

at WebDriverManager.Services.Impl.BinaryService.SetupBinary(String url, String zipPath, String binaryPath)

at WebDriverManager.DriverManager.SetUpDriverImpl(String url, String binaryPath)

at WebDriverManager.DriverManager.SetUpDriver(IDriverConfig config, String version, Architecture architecture)

**Comment by ms6073** [comment]
Referring to the WebDriverManager code, it typically saves to the Windows 'temp' folder ("C:\Users\<username>\AppData\Local\Temp\").

`public static string GetZipDestination(string url)
 {
        var tempDirectory = Path.GetTempPath();
        var guid = Guid.NewGuid().ToString();
        var zipName = Path.GetFileName(url);
        if (zipName == null) throw new ArgumentNullException($"Can't get zip name from URL: {url}");
       return Path.Combine(tempDirectory, guid, zipName);
 }`

**Comment by rosolko** [comment]
Work as designed
