### ISSUE TITLE
InvalidOperationException: This version of ChromeDriver only supports Chrome version X (SessionNotCreated)

### ISSUE THREAD

**Issue by StanlyLife** [rosolko/WebDriverManager.Net#90]
**InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 83 (SessionNotCreated)**

I am fairly new to web scraping, especially with web drivers. However, I have searched far and wide for a solution to the ChromeDriver compatibility issues and it seems like this package should fix that issue. As I am still receiving the same error and could not find a solution in the "docs" to this package I decided to post an issue and see if anyone could help.
____

My main lines of code are
```
			**new DriverManager().SetUpDriver(new ChromeConfig());**
			var chromeoptions = new ChromeOptions();
			var seleniumConfigService = new SeleniumConfigService();
			chromeoptions = seleniumConfigService.SetDefaultChromeConfig(chromeoptions);
			var driver = new ChromeDriver(chromeoptions);
```
the project file can be found [Here](https://github.com/StanlyLife/UtviklerJobb-WebScraper-API/blob/master/web_scraper/Interfaces/JobRetrievers/JobregScraper.cs)
____

and the error still persists:

```
InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 83 (SessionNotCreated)
OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
```

```
System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 83 (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeDriverService service, ChromeOptions options, TimeSpan commandTimeout)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(ChromeOptions options)
   at web_scraper.Interfaces.JobRetrievers.JobregScraper.CheckForUpdates(Boolean checkCategories) in C:\Users\stian\Documents\.VS CODE\. Net\web_scraper\Interfaces\JobRetrievers\JobregScraper.cs:line 57
   at web_scraper.Controllers.JobregWebScraperController.GetAsync() in C:\Users\stian\Documents\.VS CODE\. Net\web_scraper\Controllers\JobregWebScraperController.cs:line 38
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by rosolko** [comment]
@StanlyLife Can you please check your *Chrome browser* and *Chrome driver* versions.

**Comment by StanlyLife** [comment]
@rosolko Thank you for taking your time and investigating the issue. it seems like my chrome is of version 85.
____
```
**Google Chrome** | 85.0.4183.83 (official version) (64-bit) (cohort: 85_83_Win)
**Versjon** | 94abc2237ae0c9a4cb5f035431c8adfb94324633-refs/branch-heads/4183@{#1658}
**OS** | Windows 10 OS Version 1903 (Build 18362.1016)
```
___

However, in the console of the application, it seems to be running (driver) version `83.0.4103.39`

```
Starting ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) on port 56769
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

I thought _WebDriverManager_ was supposed to update this automatically(?)

**Comment by deborahdcarlo** [comment]
Hey @rosolko  I am having the same problem as @StanlyLife , I have version 85.0.4183.83 in chrome browser, however, it seems that the manager is not being able to update automatically to the latest chromeDriver, which is 85.0.4183.8700, it is trying to use the version 83 instead. 

I also thought the WebDriverManager would pick up the latest version of the driver automatically.

**Comment by StanlyLife** [comment]
@rosolko Any thoughts?

**Comment by StanlyLife** [comment]
UPDATE
______

Turns out I had installed Selenium.webdrivers.chrome and it was referring to version 83 of the extension... I downgraded to 81 to test and the same error message occurred except it said 81, not 83. I then removed that extension due to browser incompatibility and manually downloaded the driver and set envpath variables, this works.

I then removed the path from `ChromeDriver(@"C:\WebDrivers", chromeoptions);` and it automatically targets the former extension's version and tries to initiate a webdriver of version 81.

So I looked  through the documentation again and saw:

> Notice that simply adding new DriverManager().SetUpDriver(<config>) does magic for you:
> It checks the latest version of the WebDriver binary file
> It downloads the binary WebDriver if it is not present in your system

Does this mean that It will not update the webdriver automatically if there already is an older version located on the computer? If that is the case how does the extension check or rather where the other webdrivers exists?

**Comment by StanlyLife** [comment]
Update
______

Adding `new DriverManager().SetUpDriver(new ChromeConfig(), "Latest", Architecture.X64);` Installed webdriver inside project folder. However, selenium does not seem to take the webdriver into consideration and is not using it without it beeing specified

**Comment by Dimitvp** [comment]
I think that your initial implementation, in the very first comment above, it is perfectly fine. I am using the same one and it is working in Production. 

> Does this mean that It will not update the webdriver automatically if there already is an older version located on the computer? If that is the case how does the extension check or rather where the other webdrivers exists?

I am not sure but I think, Yes, this is what does this mean.
I was used to add the WebDriver in my project manually and use it the same way as you do. But since I am using the WebDriver Manager I **Deleted** the driver from my project and I am letting the Manager to deal with that. After all it is Downloading the Latest Version, even if you look closer into the source code it is doing exactly that.
So my guess is that if you Remove the driver from your project all together and let the Manager do it's magic it will solve you problem ;) 

Well here comes the other problem. Sometimes the Chrome is updating by itself(there are some ways to stop that but I am not a fan). In this case you have to restart your program(winService or whatever) and the Manager will download the latest version.
Probably there are ways to automate even that but this is different subject. Also in this issue #85 they implemented useful feature if you don`t want to update your browser.
